### ISSUE TITLE
FitINLA function(), fitted model 

### ISSUE THREAD

**Issue by acquijanoa** [richardli/SUMMER#11]
Hi, I fitted a Spatio-temporal smoothing model for under-five mortality rates with SUMMER package, specifically with fitINLA function. The related references (mercer et al, Li, et al) shows that the fitted yearly-model is a Spatio-temporal one with spatial structured and unstructured effect (ICAR, iid), also structured and unstructured temporal effect (RW2, iid) and the Spatio-temporal interaction based in Knorr. However, when I fitted the model and summarized it the unstructured random effect was not included and most of them are "generic" which means, an iid model for all of them.  Moreover, I tried modifying the function but the latent model objects iid.new, rw.model are hidden and R doesn't recognize it. 
![Screen Shot 2019-10-20 at 9 30 36 AM](https://user-images.githubusercontent.com/18736362/67161083-aedf1480-f31c-11e9-8d5d-2beeb13e7a15.png)

thanks

**Comment by richardli** [comment]
Hi, 

>when I fitted the  model and summarized it the unstructured random effect was not included 

Which unstructured random effect is not included? They are time.unstruct, and within region.struct. The BYM2 model contain both structured and unstructured parts. See https://inla.r-inla-download.org/r-inla.org/doc/latent/bym2.pdf

>and most of them are "generic" which means, an iid model for all of them.

The RGeneric2 refers to the internal functions we use to code the random effects on yearly level with input on multi-year intervals, since they are not standard INLA latent models. 

So the time.struct here is a period-to-year RW2, time.unstruct is a period-to-year iid, and time.area is a period-to-year type IV interaction, as you specified in the function call. 

You can verify the posterior distribution by using the getDiag() function, to confirm the structured ones are indeed smooth. 

The period-to-year model can be revealed using commands such as ``SUMMER:::rw.new``. They are not exported, but can be shown with the ``:::`` syntax.
