### ISSUE TITLE
Unclear error in getBirths

### ISSUE THREAD

**Issue by krpaulson** [richardli/SUMMER#37]
Hi Richard -- I'm getting the following error with getBirths which is unclear to me. Can you please take a look? I'll email you the data file.
Thanks,
Katie

``` r
data.raw <- readRDS("~/Desktop/data.raw.rds")
data <- SUMMER::getBirths(
  data = data.raw,
  surveyyear = 1996,
  year.cut = seq(1970, 1997, 1),
  variables = intersect(c("caseid", "v001", "v002", "v004", "v005", "v021", "v022", "v023", "v024",
                          "v025", "v101", "v102", "v139", "bidx", "v012"), names(data.raw)),
  strata = intersect(c("v022", "v024", "v025", "v101", "v102"), names(data.raw)),
  compact = F
)
#> Children with age at least 24 months are assumed to have recorded age truncated to full years. 
#> Recorded age + 5 months is used to adjust for the truncation for ages >= 24 and are multiples of 12.
#> Error in `$<-.data.frame`(`*tmp*`, "age", value = "0"): replacement has 1 row, data has 0
```

<sup>Created on 2024-01-25 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by richardli** [comment]
It seems the dob of observations are from 1916 to 1953 if you reverse the CMC = (year - 1900) * 12 + month calculation. That's why there's no data during the specified period. Could be an original data issue?
> summary(data.raw$b3)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  198.0   441.0   515.0   502.8   577.0   638.0

I have added more informative error messages to the package.
