### ISSUE TITLE
INLA Repo in Vignette

### ISSUE THREAD

**Issue by bryandmartin** [richardli/SUMMER#5]
INLA Repository in the Vignette was not updated in v0.2.1. Should match DESCRIPTION file.

**Comment by richardli** [comment]
done

**Comment by liuyanguu** [comment]
(Just a comment) Thanks for the great vignettes. They were very well written. Impressive work. 
I guess in order to please the cran all the scripts were removed and only the _htmls_ were kept (actually it is great, I didn't know that vignette could be inserted this way). 
Maybe this is the reason while using `browseVignettes` the "source" doesn't really go anywhere.
![image](https://user-images.githubusercontent.com/11966330/85643454-27dbfc00-b662-11ea-8e46-22178f7c3762.png)

**Comment by richardli** [comment]
Thank you, and yes the support to static vignettes from CRAN (or R in general) are not very friendly...so it's difficult to test what browseVignettes will look like and how to change it. I may change to dynamic vignettes if I can figure out how to avoid complaining it takes too long...
